---
# tasks file for 2PRecuperatorio
- name: "Crear usuario Profesor"
  user:
    name: profesor
    group: GProfesores
    createhome: yes
    state: present

- name: "Crear usuario Alumno"
  user:
    name: alumno
    group: GAlumnos
    createhome: yes
    state: present

- name: "Crear grupo GProfesores"
  group:
    name: GProfesores
    state: present

- name: "Crear grupo GAlumnos"
  group:
    name: GAlumnos
    state: present


